### ISSUE TITLE
 illegal hardware instruction 

### ISSUE THREAD

**Issue by EliaHKM** [hwittenborn/tap#1]
hi,
I've tried tap but it gives me this output
`❯ tap search exa-bin
`  
`[1]    20927 illegal hardware instruction  tap search exa-b`
I'm using the latest version of tap (0.4.0-1)

**Comment by hwittenborn** [comment]
I'm really starting to think it might be something with Devuan, as I can't reproduce both the mpm error and this one on my machine:

```
hunter@hwittenborn-laptop:~/temp/tap$ tap search exa-bin
exa-bin/0.10.1-1
  Description: Replacement for ls written in Rust
  Maintainer: only_vip
  Votes: 0
  Out of Date: N/A
  Last Modified: 2021-07-07
```

Would you know Debian release Devuan is based on?

**Comment by hwittenborn** [comment]
I'm really starting to think it might be something with Devuan, as I can't reproduce both the mpm error and this one on my machine:
```
> tap search exa-bin
exa-bin/0.10.1-1
  Description: Replacement for ls written in Rust
  Maintainer: only_vip
  Votes: 0
  Out of Date: N/A
  Last Modified: 2021-07-07
```

Would you know Debian release Devuan is based on?

**Comment by EliaHKM** [comment]
it's based on Debian 10 buster

**Comment by EliaHKM** [comment]
I find out what's the problem 
it's homebrew 
after uninstalling it 
tap start working 
so I will close the case
thank you for your help
cheer
