### ISSUE TITLE
MPR dependencies aren't working

### ISSUE THREAD

**Issue by hwittenborn** [hwittenborn/tap#15]
Attempting to install a package like `img4tool-git` isn't working properly, and is resulting in an error about dependencies not being able to be found (though they should be findable via the MPR).

**Comment by gamer4life1** [comment]
I am going to compile my changes locally to see if my PR fixes this issue.

**Comment by hwittenborn** [comment]
Closing as I don't know if I want to support MPR dependencies just yet. If anyone else wants them feel free to open up a new issue.
