### ISSUE TITLE
Packages with dependencies are broken

### ISSUE THREAD

**Issue by lpuv** [hwittenborn/tap#17]
Until my PR #14 gets merged to fix some typos caused in the function that builds a dependency tree, packages that require dependencies are broken. I have tested with a locally compiled version of tap with my patch and it seems to work.

This is purely for reference.

:)

**Comment by gamer4life1** [comment]
Wait, not actually sure whether this applies to all packages or the ones just with distro specific dependencies.

**Comment by gamer4life1** [comment]
@hwittenborn :)
