### ISSUE TITLE
Feature request: Use $VISUAL and $EDITOR environment variables instead of nano to edit PKGBUILD and other files

### ISSUE THREAD

**Issue by vyashole** [hwittenborn/tap#2]
Instead of using nano as the editor, `tap` should respect the user's settings and use their default editors (e.g. vim, emacs, gvim, etc) 

Debian Policy recommends this behavior: https://www.debian.org/doc/debian-policy/ch-customized-programs.html#editors-and-pagers

Suggestion: 
If `VISUAL` is set, use `VISUAL`
else if `EDITOR` is set use `EDITOR`
else use `/usr/bin/editor` which is set to `nano` by default on Debian and most derivatives. 
as a fallback, use `nano` directly

P.S. I'll be happy to raise a pull request in some time,. Maybe I'll need a little bit of help with code style, etc. :)

**Comment by hwittenborn** [comment]
This is something that was on my backplate with both tap and mpm, but was just awaiting someone to actually request it (felt too lazy to add a feature no one was requesting).

Anyway, since you already got all the work done, I'll do some local testing shortly (might be a couple days, busy with some other stuff) and will merge it if it all works fine.

**Comment by vyashole** [comment]
Thank you very much :)

**Comment by hwittenborn** [comment]
See https://github.com/hwittenborn/tap/pull/3 for some more info on why the relevant PR wasn't merged.

Regarding making some notes on coding styles, I think I'll try to add some notes on what I prefer at some point.

If you make any future contributions, the following would be a good motto to go off of:

- If you can put something into a function inside of a separate file, do it.
- When doing so, add `# REMOVE AT PACKAGING` to the end of the `from import` line (all functions get put into one file at build time).

Pretty simple, it's how I like to keep things clean though. If PRs end up getting to be a bit more active here, I'll consider a more thorough write-up on how I'd like things done.
