### ISSUE TITLE
[Feature request] Adding a list-installed option

### ISSUE THREAD

**Issue by not-a-dev-stein** [hwittenborn/tap#6]
The only way right now to check MPR installed packages is through this long command I only knew about in the last tap update, to check packages affected by the updating issue:

`dpkg-query --show --showformat '${Package}/${MPR-Package}\n' | grep '^[^/]*/True' | awk -F '/' '{print $1}'`

It would be a nice quality-of-life improvement to have an option built into tap to check what packages you installed through it, with something like:

`tap list-installed`

**Comment by hwittenborn** [comment]
I just pushed a commit that adds a feature for listing all packages installed from the MPR (or any that uses the spec that Tap uses) which uses the `list-installed` command like you recommended.

Currently, the format looks like this (and it just repeats for all packages installed from the MPR):

```
Package/Version
  From: {pkgbase from PKGBUILD used to build package}
```

I'm thinking about adding the packages description to the output, but is there anything else you'd like added?

**Comment by not-a-dev-stein** [comment]
> {Package}/{Version}
  From: {pkgbase from PKGBUILD used to build package}
  Description: {Description}
  Maintainer: {Maintainer}
I really like it, but wouldn't it be better to have it the old way as the default and have this version with description, maintainer (and maybe package size) with a `--verbose` option?

**Comment by hwittenborn** [comment]
> It'd make it easier to scroll and search if the user needs to scroll having to look for one among a lot of packages installed.

I just added a feature that pipes the output of 'list-packages' into `less` when the output is taller than the terminal height - would that work for you, or do you still want the old way where it just lists the package, version, and source on the MPR?

> that is a BottomUp list option

How exactly would that work? I'm not really even remotely familiar with what that is lol.

> I've been having this issue when trying to update tap

It looks like Tap isn't able to delete the old build directory used to build packages - could you try deleting it manually? (The directory in question is `/var/tmp/mpm`.)

Though Tap *should* be complaining if it can't delete the old build directory - I'll have to look into that if that's indeed the source of the issue.

**Comment by not-a-dev-stein** [comment]
> could you try deleting it manually? (The directory in question is /var/tmp/mpm.)

I ended up managing to install it correctly by downloading the PKGBUILD from the MPR and using makedeb on it directly.

> How exactly would that work? I'm not really even remotely familiar with what that is lol.

It's an option with AUR helpers like yay or paru, what it does is basically reverse the order of packages so you don't have to scroll all the way to the start to see the list in alphabetical order, so it'd have to be something that reverses the list order and prints it from Z-A instead of A-Z. 
Not sure if there's a way to implement it, but it'd be nice if it could be done, at least piping it into `less` is a good choice, but it'd be nice if there was an option to pipe it into `bat` if the user has it installed to get those sweet sweet colors.

**Comment by hwittenborn** [comment]
> reverses the list order and prints it from Z-A instead of A-Z

Doesn't sound too hard, I imagine there's probably already something implemented in Python for it.

> it'd be nice if there was an option to pipe it into bat if the user has it installed to get those sweet sweet colors

From the things I've read, `bat` just does syntax highlighting, right? If so, there would really be any "syntax" to go from, as I'm kind of just arbitrarily adding some strings.

I do have it currently set to highlight the package name though (think of it like `{green}Package{normal}/Version`). Don't know what it'd look like if more would be highlighted, but I'm down for ideas.

**Comment by not-a-dev-stein** [comment]
Just installed the most recent version with the --rev-alpha option and it works great.

I feel like at least for the foreseeable future we don't need that --verbose idea, but it would be a nice to have if instead of different lines for "Out of Date" and "Last Modified" went in the same line as the package name and version line, like this (with also showing if the package is already installed during a search being another idea that I'll probably open a different feature request later):

```
package-name/version number/last modified date (Out of date or Orphaned) (+ or - ratio of votes) [Installed]
Description: lorem ipsum etc etc
Maintainer: name of maintainer
```

```
package-name/version number (+ or - ratio of votes) [Installed]
Description: lorem ipsum etc etc
Maintainer: name of maintainer
Last Modified: last modified date (Out of date or Orphaned)
```

So something like this:

```
makedeb/5.9.5-1/2021-07-24 (Out-of-date | 2021-08-02) (+1) [Installed]
Description: Create Debian archives from PKGBUILDs (stable release)
Maintainer: hwittenborn
```

```
makedeb/5.9.5-1 (+1) [Installed]
Description: Create Debian archives from PKGBUILDs (stable release)
Maintainer: hwittenborn
Last Modified: 2021-07-24 (Out-of-date | 2021-08-02)
```
 
With it being prompted like this you could also color the (Out of date) prompt with red and the votes count with green and the [Installed] with blue, for example.

**Comment by hwittenborn** [comment]
The main styling I was wanting to use was the one that's used for the `search` command, where it's also the package and version on one line, followed by everything else on separate lines.

The main idea was to follow the styling APT uses, with some changes to fit better with the extra info like current maintainer, out of date status, etc.

I'd be fine with adding the `[Installed]` thing on the first line when searching for packages though (just wouldn't show up for packages that aren't installed). I'd also be open to seeing how to put the out of date info on the last modified line.

**Comment by not-a-dev-stein** [comment]
> The main idea was to follow the styling APT uses

Oh, makes sense, in this case I'd come back to suggesting having minimal info by default and adding a `--verbose` option to the search, that could look something like this:

`tap search package-name`
```
package-name/version number (+ or - ratio of votes) [Installed]
Description: lorem ipsum etc etc
```
`tap search --verbose package-name` or `tap search -v package-name`
```
package-name/version number (+ or - ratio of votes) [Installed]
Description: lorem ipsum etc etc
Maintainer: name of maintainer
Last Modified: last modified date (Out of date or Orphaned)
```
OR
```
package-name/version number [Installed]
Description: lorem ipsum etc etc
Votes: n. of votes / % of votes
Maintainer: name of maintainer
Last Modified: last modified date (Out of date or Orphaned)
```
This would make the need to pipe the output to `less` less likely to happen while still keeping most of the essential info the person looking for the package needs.
 
I still think having the vote ratio counter in the same line is better (including the non-verbose option), since apt doesn't have a similar counter for their repos and it takes one less line having it there, which can make regular searches better (I know I pay attention to n. of votes when searching AUR stuff with yay or paru, I'm certain that there are more people that do so). Like, it takes a minimal amount of space, and it can help a lot in the future, when there are more packages and more people voting on those packages, it's a more future-proof concept.

But yeah, `list-packages` is pretty much perfect the way it is, I wouldn't change it.

**Comment by hwittenborn** [comment]
I'm really just not a fan of the `(+num)` syntax. Something about it just isn't doesn't look good to me. If you feel like you can convince me otherwise, feel free to do so though :)

Regarding everything else then:

I added a `-e`/`--min-info` option to display less output when searching. Currently (when you specify the option), it'll display the package name, description, version, and out of date status like so:

```
pkgname/version
  Description: pkgdesc
  Out of Date: N/A
```
---

I also thought it might be a bit tedious to have to pass that option every time you run Tap (I was assuming you'd do so), so I also added the ability to pass long options to Tap via environment variables (excluding `--help` and `--version`, logically). All you need to do is set the environment variable to **something**, even a blank string would do.

To construct the environment variable, you'd do the following:

1. Remove the `--` prefix
2. Replace all `-` with `_`
3. Make the resulting string uppercase
4. Prefix *that* resulting string with `TAP_MPR_`

Likewise, you would do the following to pass the `--min-info` option via an environment variable:

```sh
TAP_MPR_MIN_INFO="" tap search package
```

You could also do this if it would make it easier to keep in a `.bashrc` file or something similar:

```sh
export TAP_MPR_MIN_INFO=""
tap search package
```

**Comment by not-a-dev-stein** [comment]
Oh, that's good, ideally there would be a tap.conf file in the future for editing these kinds of things instead of environmental variables, but I like this approach for now, since there aren't other options to configure other than that.

**Comment by hwittenborn** [comment]
Is there any reason the environment variables approach doesn't suit you well? I just feel like having a config file (for what is currently only three available options) is a bit overkill when you could just set some environment variables.

If the available options were to ever increase in a way that would deem a config file, I'd probably implement something then, but I don't feel like one would be needed for just a couple of (not even mandatory) options.

Again, feel free to convince me otherwise if you feel like you'd indeed rather have a config file. I'll be closing the issue as the very original topic has since been solved, and everything since then has mostly been tiny refinements related to it.

**Comment by not-a-dev-stein** [comment]
> I just feel like having a config file (for what is currently only three available options) is a bit overkill when you could just set some environment variables.

 yeah, I was suggesting it for the future, when more options are available, for now the environment variable is more than enough

**Comment by hwittenborn** [comment]
Sounds good. I'll look into it more when the time comes for it being needed then.
