### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by hwittenborn** [hwittenborn/tap#7]
This issue is meant to serve as a roadmap for everything that needs to take place before a v1.0.0 release can be made.

The reason for making this now instead of earlier is that I feel like I'm able to now see what all needs to be done, contrary to me not being able to do such previously.

Note that this list will not contain all features that are planned to be added, but rather only those that I'd like to be present at a 1.0.0 release.

### Tasks
- [x] Installation functionality
- - [x] Package building
- - [x] Package installation
- - [x] Reliable dependency solving
- - - [x] Distro-specific dependencies
- - - [x] Architecture-specific dependencies
- - - [x] Reliable dependency parsing (i.e. building a dependency tree correctly)
- [x] Update functionality
- - [x] Updates for standard MPR packages
- [x] Searching functionality

**Comment by gamer4life1** [comment]
sooo... v1.0.0? 🚀

**Comment by hwittenborn** [comment]
Pretty much, I just want to keep it out for a bit so everything can be tested by end users.

If everything seems good on Saturday or so I'll go ahead and make v1.0.0.
