### ISSUE TITLE
Dependencies missing while trying to install a package

### ISSUE THREAD

**Issue by onlyvip** [hwittenborn/tap#9]
I tried installing rofi via tap as follows `tap install rofi` however it stops at the dependencies check and install step in makedeb and makepkg here's a screenshot of the same
https://ezup.dev/p/r64m7e

**Comment by hwittenborn** [comment]
From my brief checking, this issue appears to be rooted somewhere in part of Tap's code that's going to be removed after some features of makedeb make their way to the stable release.

That means that the issue's probably just going to be unresolved for the time being, but it shouldn't be too long before makedeb's new features are migrated over.

**Comment by hwittenborn** [comment]
Looks like I found the issue (the lines in question are [here](https://github.com/hwittenborn/tap/blob/main/src/functions/build_dependency_packages.py#L24)).

`get_srcinfo_value(j, False)` should be `get_srcinfo_value(j, True)` (the `False` and `True` statements define if Tap should look for lines that start with a tab or not, which dependencies **do** start with).

Issue should hopefully be fixed shortly.

**Comment by onlyvip** [comment]
What's tab?

**Comment by hwittenborn** [comment]
A tab is like a space, but your system can define how big it is.

You can see how it works with a command like this in your terminal:

```sh
echo -e '\ttest'
```

That prints a tab followed by the word `test`.

**Comment by onlyvip** [comment]
So suppose I use space instead of tab in the depends array set would that
affect tap detecting them as dependencies?

**Comment by hwittenborn** [comment]
No, it's only in the `.SRCINFO` file, which makedeb generates for you.

**Comment by onlyvip** [comment]
Makes sense then. Thanks for clarifying 😌
